[package]
name = "raytrace-rs"
version = "0.1.0"
authors = ["tkchanat <andychancse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
chrono = "0.4.15"
image = "0.23.9"